"""initial schema

Revision ID: 30ec096021cb
Revises: 
Create Date: 2026-07-13 20:35:37.083797
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30ec096021cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brokers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('areas_covered', sa.String(length=512), nullable=True),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brokers_name'), 'brokers', ['name'], unique=False)
    op.create_table('comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparisons_name'), 'comparisons', ['name'], unique=True)
    op.create_table('preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('size_min_sqft', sa.Float(), nullable=True),
    sa.Column('size_max_sqft', sa.Float(), nullable=True),
    sa.Column('budget_max', sa.Float(), nullable=True),
    sa.Column('locations', sa.JSON(), nullable=False),
    sa.Column('required_features', sa.JSON(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preferences_name'), 'preferences', ['name'], unique=True)
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('survey_number', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('taluk', sa.String(length=128), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=False),
    sa.Column('total_area_sqft', sa.Float(), nullable=True),
    sa.Column('asking_price', sa.Float(), nullable=True),
    sa.Column('price_per_sqft', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('evaluating', 'shortlisted', 'rejected', 'purchased', name='propertystatus'), nullable=False),
    sa.Column('water_source', sa.String(length=64), nullable=True),
    sa.Column('electricity', sa.String(length=64), nullable=True),
    sa.Column('road_access', sa.String(length=64), nullable=True),
    sa.Column('corner_plot', sa.Boolean(), nullable=True),
    sa.Column('estimated_appreciation_pct', sa.Float(), nullable=True),
    sa.Column('rental_yield', sa.String(length=32), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_asking_price'), 'properties', ['asking_price'], unique=False)
    op.create_index(op.f('ix_properties_location'), 'properties', ['location'], unique=False)
    op.create_index(op.f('ix_properties_name'), 'properties', ['name'], unique=True)
    op.create_index(op.f('ix_properties_status'), 'properties', ['status'], unique=False)
    op.create_index(op.f('ix_properties_survey_number'), 'properties', ['survey_number'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('broker_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('shown_date', sa.Date(), nullable=True),
    sa.Column('asking_price', sa.Float(), nullable=True),
    sa.Column('broker_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparison_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comparison_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparisons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('neighbors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('survey_number', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.Enum('north', 'south', 'east', 'west', name='direction'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('shared_boundary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_neighbors_survey_number'), 'neighbors', ['survey_number'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subdivisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('survey_number_full', sa.String(length=64), nullable=True),
    sa.Column('area_sqft', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subdivisions_survey_number_full'), 'subdivisions', ['survey_number_full'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('subdivision_id', sa.Integer(), nullable=True),
    sa.Column('neighbor_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('doc_type', sa.Enum('patta', 'fmb', 'ec', 'deed', 'land_record', 'notes', 'photo', 'document', 'unknown', name='documenttype'), nullable=False),
    sa.Column('status', sa.Enum('missing', 'uploaded', 'verified', 'issues_found', 'expired', name='verificationstatus'), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('extracted_survey_number', sa.String(length=64), nullable=True),
    sa.Column('extracted_owner_name', sa.String(length=255), nullable=True),
    sa.Column('extracted_extent', sa.String(length=64), nullable=True),
    sa.Column('extracted_village', sa.String(length=128), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['neighbor_id'], ['neighbors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subdivision_id'], ['subdivisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_extracted_survey_number'), 'documents', ['extracted_survey_number'], unique=False)
    op.create_index(op.f('ix_documents_neighbor_id'), 'documents', ['neighbor_id'], unique=False)
    op.create_index(op.f('ix_documents_property_id'), 'documents', ['property_id'], unique=False)
    op.create_index(op.f('ix_documents_subdivision_id'), 'documents', ['subdivision_id'], unique=False)
    op.create_table('survey_boundaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('neighbor_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('srid', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['neighbor_id'], ['neighbors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_vertices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boundary_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['boundary_id'], ['survey_boundaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_vertices')
    op.drop_table('survey_boundaries')
    op.drop_index(op.f('ix_documents_subdivision_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_property_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_neighbor_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_extracted_survey_number'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_subdivisions_survey_number_full'), table_name='subdivisions')
    op.drop_table('subdivisions')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_neighbors_survey_number'), table_name='neighbors')
    op.drop_table('neighbors')
    op.drop_table('comparison_items')
    op.drop_table('broker_properties')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_properties_survey_number'), table_name='properties')
    op.drop_index(op.f('ix_properties_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_name'), table_name='properties')
    op.drop_index(op.f('ix_properties_location'), table_name='properties')
    op.drop_index(op.f('ix_properties_asking_price'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_preferences_name'), table_name='preferences')
    op.drop_table('preferences')
    op.drop_index(op.f('ix_comparisons_name'), table_name='comparisons')
    op.drop_table('comparisons')
    op.drop_index(op.f('ix_brokers_name'), table_name='brokers')
    op.drop_table('brokers')
    # On PostgreSQL the native ENUM types created implicitly by create_table are
    # not removed by drop_table; drop them so a re-upgrade doesn't fail with
    # "type already exists". (No-op on SQLite, which has no native enum types.)
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        for enum_name in ("propertystatus", "direction", "documenttype", "verificationstatus"):
            sa.Enum(name=enum_name).drop(bind, checkfirst=True)
    # ### end Alembic commands ###
